import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Auth root',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <nav className='flex gap-5 p-5 border-slate-400 border-b-[1px]'>
        <Link href='/login'>Login</Link>
        <Link href='/signup'>SignUp</Link>
      </nav>
      {children}
    </main>
  );
}
